---
- include: deploy_monitors.yml
  when: not ceph_containerized_deployment

- include: start_monitor.yml
  when: not ceph_containerized_deployment

- include: ceph_keys.yml
  when: not ceph_containerized_deployment

- include: create_mds_filesystems.yml
  when: not ceph_containerized_deployment and mds

- include: secure_cluster.yml
  when: secure_cluster and not ceph_containerized_deployment
  tags: secure_cluster

- include: docker.yml
  when: ceph_containerized_deployment
