---
- include: deploy_monitors.yml
  when: not ceph_containerized_deployment

- include: ceph_keys.yml
  when: not ceph_containerized_deployment

- include: ceph_keys.yml
  when: not ceph_containerized_deployment

- include: docker.yml
  when: ceph_containerized_deployment
