---
- name: test if rbd exists
  shell: |
    "{{ docker_exec_cmd }} ceph --cluster {{ cluster }} osd pool ls | grep -sq rbd"
  changed_when: false
  failed_when: false
  run_once: true
  check_mode: true
  register: rbd_pool_exist

- name: include rbd_pool_df.yml
  include: rbd_pool_df.yml
  when: rbd_pool_exist.rc == 0

- name: include rbd_pool_pgs.yml
  include: rbd_pool_pgs.yml
  when:
    - rbd_pool_exist.rc == 0
    - ceph_conf_overrides.get('global', {}).get('osd_pool_default_pg_num', False) != False

- name: include rbd_pool_size.yml
  include: rbd_pool_size.yml
  when:
    - rbd_pool_exist.rc == 0
    - ceph_conf_overrides.get('global', {}).get('osd_pool_default_pg_num', False) != False
