---
- name: start the monitor service
  service:
    name: ceph-mon@{{ monitor_name }}
    state: started
    enabled: yes
  changed_when: false

- name: enable ceph-mon.target service
  service:
    name: ceph-mon.target
    enabled: yes
  changed_when: false
