---
- name: create bootstrap directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/ceph/
    - /var/lib/ceph/bootstrap-osd
    - /var/lib/ceph/bootstrap-mds
    - /var/lib/ceph/bootstrap-rgw

# NOTE (leseb): for version 1.1.0 because https://github.com/ansible/ansible-modules-core/issues/1227
- name: install docker-py
  pip:
    name: docker-py
    version: 1.1.0
